<?php
/**
 * Created by PhpStorm.
 * User: liuhao
 * Date: 2016/1/29
 * Time: 7:25
 */
//header("Content-Type: text/html;charset=utf-8");


require('BasePage.php');
class Carpart extends BasePage{
    function init(){
        parent::init();
        $this->tablename="carpart";
        $this->id_field="id";
        $this->head = array(array('name' => 'id', 'editable' => 0, 'display' => 1, 'showname' => 'ID', 'type' => ''),
            array('name' => 'oe', 'editable' => 1, 'display' => 1, 'showname' => 'OE号', 'type' => ''),
            array('name' => 'name', 'editable' => 1, 'display' => 1, 'showname' => '名字', 'type' => ''),
            array('name' => 'ename', 'editable' => 1, 'display' => 1, 'showname' => '标准名字', 'type' => ''),
            array('name' => 'defaultimg', 'editable' => 1, 'display' => 1, 'showname' => '默认图片', 'type' => ''),
            array('name' => 'cateid', 'editable' => 1, 'display' => 1, 'showname' => '类别id', 'type' => ''),
            array('name' => 'source', 'editable' => 1, 'display' => 1, 'showname' => '来源', 'type' => ''),
            array('name' => 'isfrom_orifactory', 'editable' => 1, 'display' => 1, 'showname' => '是否原厂件', 'type' => ''),
            array('name' => 'isfrom_homofactory', 'editable' => 1, 'display' => 1, 'showname' => '是否同质件', 'type' => ''),
            array('name' => 'isfrom_abroad', 'editable' => 1, 'display' => 1, 'showname' => '是否海外件', 'type' => ''),
            array('name' => 'factory_href', 'editable' => 1, 'display' => 1, 'showname' => '原厂链接', 'type' => ''),
        );
        $this->columnNum = count($this->head);

        $this->edit_url = "carpart.php?action=edit";
        $this->del_url =  "carpart.php?action=del";
        $this->add_url =  "carpart.php?action=add";

        $this->aikey = "id";
    }
    function showPage(){
        return parent::showPage();
    }
    function execute()
    {


        return parent::execute(); // TODO: Change the autogenerated stub
    }
}

$mclass=new Carpart();
$mclass->init();
$mclass->execute();


