<?php
/**
 * Created by PhpStorm.
 * User: liuhao
 * Date: 2016/1/29
 * Time: 7:25
 */
//header("Content-Type: text/html;charset=utf-8");


require('BasePage.php');
class Carpart extends BasePage{
    function init(){
        parent::init();
        $this->tablename="carpart";
        $this->id_field="id";
        $this->head = array(array('name' => 'id', 'editable' => 0, 'display' => 1, 'showname' => 'ID', 'type' => ''),
            array('name' => 'oe', 'editable' => 1, 'display' => 1, 'showname' => 'OE号', 'type' => ''),
            array('name' => 'name', 'editable' => 1, 'display' => 1, 'showname' => '名字', 'type' => ''),
            array('name' => 'ename', 'editable' => 1, 'display' => 1, 'showname' => '标准名字', 'type' => ''),
            array('name' => 'defaultimg', 'editable' => 1, 'display' => 0, 'showname' => '默认图片', 'type' => ''),
            array('name' => 'cateid', 'editable' => 1, 'display' => 1, 'showname' => '类别id', 'type' => ''),
            array('name' => 'source', 'editable' => 1, 'display' => 1, 'showname' => '来源', 'type' => ''),
            array('name' => 'isfrom_orifactory', 'editable' => 1, 'display' => 1, 'showname' => '是否原厂件', 'type' => ''),
            array('name' => 'isfrom_homofactory', 'editable' => 1, 'display' => 1, 'showname' => '是否同质件', 'type' => ''),
            array('name' => 'isfrom_abroad', 'editable' => 1, 'display' => 1, 'showname' => '是否海外件', 'type' => ''),
            array('name' => 'factory_href', 'editable' => 1, 'display' => 0, 'showname' => '原厂链接', 'type' => ''),
        );
        $this->columnNum = count($this->head);

        $this->edit_url = "carpart.php?action=edit";
        $this->del_url =  "carpart.php?action=del";
        $this->add_url =  "carpart.php?action=add";

        $this->aikey = "id";
    }
    function showPage(){
        return parent::showPage();
    }
    function execute()
    {


        return parent::execute(); // TODO: Change the autogenerated stub
    }
	
	function outFilter($data){
		$source_enum=array(0=>'自由品牌件',1=>'原厂件',2=>'再制造件',3=>'其他',4=>'代理品牌件',5=>'同质配套',6=>'海外件',8=>'拆车件');
		if(array_key_exists($data[6],$source_enum)){
			$data[6]=$source_enum[$data[6]];
		}

		$data[7] = $data[7] == '1' ? '是' : '否';
		$data[8] = $data[8] == '1' ? '是' : '否';
		$data[9] = $data[9] == '1' ? '是' : '否';
		
		
		return $data;
    }

    function inFilter(){
		$source_enum=array('自由品牌件'=>0,'原厂件'=>1,'再制造件'=>2,'其他'=>3,'代理品牌件'=>4,'同质配套'=>5,'海外件'=>6,'拆车件'=>8);
		
		if(array_key_exists($_POST['source'],$source_enum)){
			$_POST['source']=$source_enum[$_POST['source']];
		}
		
		$_POST['isfrom_orifactory']=$_POST['isfrom_orifactory']=='是'?'1':'0';
		$_POST['isfrom_homofactory']=$_POST['isfrom_homofactory']=='是'?'1':'0';
		$_POST['isfrom_abroad']=$_POST['isfrom_abroad']=='是'?'1':'0';
    }
}

$mclass=new Carpart();
$mclass->init();
$mclass->execute();


